### ISSUE TITLE
an issue in the check out page

### ISSUE THREAD

**Issue by hamadqr** [malsubrata/woo-wallet#42]
hi there, 
i am not sure what happened here. 
i visited the wallet page and need to add 0.50$ to my wallet.
in the checkout page i got a warning i have an error, in the debug mode i fin that: 
Notice: Undefined variable: order in /home/bpp/web/bpearlp.com/public_html/wp-content/plugins/woo-wallet/includes/helper/woo-wallet-util.php on line 470

Fatal error: Uncaught Error: Call to a member function get_items() on null in /home/bpp/web/bpearlp.com/public_html/wp-content/plugins/woo-wallet/includes/helper/woo-wallet-util.php:12 Stack trace: #0 /home/bpp/web/bpearlp.com/public_html/wp-content/plugins/woo-wallet/includes/helper/woo-wallet-util.php(470): is_wallet_rechargeable_order(NULL) #1 /home/bpp/web/bpearlp.com/public_html/wp-content/plugins/woo-wallet/includes/class-woo-wallet-payment-method.php(92): is_full_payment_through_wallet() #2 /home/bpp/web/bpearlp.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): Woo_Gateway_Wallet_payment->is_available() #3 /home/bpp/web/bpearlp.com/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php(3678): WC_Payment_Gateways->get_available_payment_gateways() #4 /home/bpp/web/bpearlp.com/public_html/wp-includes/class-wp-hook.php(288): wc_get_pay_buttons('') #5 /home/bpp/web/bpearlp.com/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array in /home/bpp/web/bpearlp.com/public_html/wp-content/plugins/woo-wallet/includes/helper/woo-wallet-util.php on line 12

**Comment by hamadqr** [comment]
i am so sorry, has been fixed after the update.
